export const languageToCountryCode = {
  af: "ZA", // Afrikaans (Güney Afrika)
  sq: "AL", // Arnavutça (Arnavutluk)
  am: "ET", // Amharca (Etiyopya)
  ar: "SA", // Arapça (Suudi Arabistan)
  hy: "AM", // Ermenice (Ermenistan)
  az: "AZ", // Azerice (Azerbaycan)
  eu: "ES", // Baskça (İspanya)
  be: "BY", // Beyaz Rusça (Beyaz Rusya)
  bn: "BD", // Bengalce (Bangladeş)
  bs: "BA", // Boşnakça (Bosna Hersek)
  bg: "BG", // Bulgarca (Bulgaristan)
  ca: "ES", // Katalanca (İspanya)
  ceb: "PH", // Cebuano (Filipinler)
  ny: "MW", // Chichewa (Malavi)
  "zh-CN": "CN", // Çince (Basitleştirilmiş, Çin)
  "zh-TW": "TW", // Çince (Geleneksel, Tayvan)
  co: "FR", // Korsikaca (Fransa)
  hr: "HR", // Hırvatça (Hırvatistan)
  cs: "CZ", // Çekçe (Çek Cumhuriyeti)
  da: "DK", // Danca (Danimarka)
  nl: "NL", // Felemenkçe (Hollanda)
  en: "US", // İngilizce (Amerika Birleşik Devletleri)
  eo: "XX", // Esperanto (Resmi Ülke Yok)
  et: "EE", // Estonca (Estonya)
  tl: "PH", // Filipino (Filipinler)
  fi: "FI", // Fince (Finlandiya)
  fr: "FR", // Fransızca (Fransa)
  fy: "NL", // Frizce (Hollanda)
  gl: "ES", // Galiçyaca (İspanya)
  ka: "GE", // Gürcüce (Gürcistan)
  de: "DE", // Almanca (Almanya)
  el: "GR", // Yunanca (Yunanistan)
  gu: "IN", // Gujarati (Hindistan)
  ht: "HT", // Haiti Creole (Haiti)
  ha: "NG", // Hausa (Nijerya)
  haw: "US", // Hawaii dili (Amerika Birleşik Devletleri)
  he: "IL", // İbranice (İsrail)
  hi: "IN", // Hintçe (Hindistan)
  hmn: "CN", // Hmong (Çin)
  hu: "HU", // Macarca (Macaristan)
  is: "IS", // İzlandaca (İzlanda)
  ig: "NG", // Igbo (Nijerya)
  id: "ID", // Endonezce (Endonezya)
  ga: "IE", // İrlandaca (İrlanda)
  it: "IT", // İtalyanca (İtalya)
  ja: "JP", // Japonca (Japonya)
  jw: "ID", // Cava dili (Endonezya)
  kn: "IN", // Kannada (Hindistan)
  kk: "KZ", // Kazakça (Kazakistan)
  km: "KH", // Kmerce (Kamboçya)
  rw: "RW", // Kinyarwanda (Ruanda)
  ko: "KR", // Korece (Güney Kore)
  ku: "IQ", // Kürtçe (Irak)
  ky: "KG", // Kırgızca (Kırgızistan)
  lo: "LA", // Laos dili (Laos)
  la: "VA", // Latince (Vatikan)
  lv: "LV", // Letonca (Letonya)
  lt: "LT", // Litvanyaca (Litvanya)
  lb: "LU", // Lüksemburgca (Lüksemburg)
  mk: "MK", // Makedonca (Makedonya)
  mg: "MG", // Malagasy (Madagaskar)
  ms: "MY", // Malayca (Malezya)
  ml: "IN", // Malayalam (Hindistan)
  mt: "MT", // Maltaca (Malta)
  mi: "NZ", // Maori (Yeni Zelanda)
  mr: "IN", // Marathi (Hindistan)
  mn: "MN", // Moğolca (Moğolistan)
  my: "MM", // Birmanca (Myanmar)
  ne: "NP", // Nepalce (Nepal)
  no: "NO", // Norveççe (Norveç)
  or: "IN", // Oriya (Hindistan)
  ps: "AF", // Peştuca (Afganistan)
  fa: "IR", // Farsça (İran)
  pl: "PL", // Lehçe (Polonya)
  pt: "PT", // Portekizce (Portekiz)
  pa: "IN", // Pencapça (Hindistan)
  ro: "RO", // Rumence (Romanya)
  ru: "RU", // Rusça (Rusya)
  sm: "WS", // Samoaca (Samoa)
  gd: "GB", // İskoç Gaelic (Birleşik Krallık)
  sr: "RS", // Sırpça (Sırbistan)
  st: "LS", // Sotho (Lesotho)
  sn: "ZW", // Shona (Zimbabve)
  sd: "PK", // Sindhi (Pakistan)
  si: "LK", // Sinhala (Sri Lanka)
  sk: "SK", // Slovakça (Slovakya)
  sl: "SI", // Slovence (Slovenya)
  so: "SO", // Somalice (Somali)
  es: "ES", // İspanyolca (İspanya)
  su: "ID", // Sundanca (Endonezya)
  sw: "KE", // Swahili (Kenya)
  sv: "SE", // İsveççe (İsveç)
  tg: "TJ", // Tacikçe (Tacikistan)
  ta: "IN", // Tamilce (Hindistan)
  tt: "RU", // Tatarca (Rusya)
  te: "IN", // Telugu (Hindistan)
  th: "TH", // Tayca (Tayland)
  tr: "TR", // Türkçe (Türkiye)
  tk: "TM", // Türkmence (Türkmenistan)
  uk: "UA", // Ukraynaca (Ukrayna)
  ur: "PK", // Urduca (Pakistan)
  ug: "CN", // Uygurca (Çin)
  uz: "UZ", // Özbekçe (Özbekistan)
  vi: "VN", // Vietnamca (Vietnam)
  cy: "GB", // Galce (Birleşik Krallık)
  xh: "ZA", // Xhosa (Güney Afrika)
  yi: "XX", // Yidce (Resmi Ülke Yok)
  yo: "NG", // Yoruba (Nijerya)
  zu: "ZA", // Zulu (Güney Afrika)
};
